import os
import glob
from PySide6.QtCore import QThread, Signal

class Conversions(QThread):

    """
    A class responsible for performing splitting on pdbqt files 
    generated by molecular docking, so that it creates 1 file per 
    pose for each pdbqt file, accepts multiple files in pdbqt format.
    """

    progress = Signal(int)
    finished = Signal()

    def __init__(self, pdbqt_files, folder_text):
        
        """
        Initializes the Conversions class with parameters for conversion.

        Parameters:
        -----------
        pdbqt_files : str
            Path to files in pdbqt format for split
        folder_text : str
            The destination folder path where the converted files will be saved.
        """

        super().__init__()
        self.maxim = 0
        self.contator = 0
        self.des_folder = folder_text + "/"
        self.ligands = pdbqt_files + "/"
        self._running = True

    def run(self):

        # Create the destination folder
        os.makedirs(self.des_folder, exist_ok=True)

        # Read the pdbqt files
        ligands_files = glob.glob(self.ligands + '*.pdbqt')
        
        for file in ligands_files:

            if not self._running:
                break
            
            # Open each file as f and read their lines
            with open(file, 'r') as f:
                lines = f.readlines()

            my_dict = {}
            temp_list = []
            con = 0
            
            # Iterate each line and save lines in their respective classification using the 
            # Model word to it
            for line in lines:
                if line.startswith("MODEL"):
                    con +=1
                    my_dict[con] = []
                my_dict[con].append(line)

            # Save the files 
            for key, list in my_dict.items():
                
                pdbqt_name = self.des_folder + os.path.basename(file).split(".")[0] + f"_{key}.pdbqt"
                
                with open(pdbqt_name,'w') as f2:
                    for line in list:
                        f2.write(line)

            self.contator +=1
            self.progress.emit(self.contator)
        
        self.finished.emit()
        
    def Maximum(self, ini_folder):
        ini_folder = ini_folder + "/"
        pdbs_files = glob.glob(ini_folder + '*.pdbqt')
        self.maxim = len(pdbs_files)
    
    def stop(self):
        self._running = False

            
                